apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-c1
  labels:
    app: hello-c1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-c1
  template:
    metadata:
      labels:
        app: hello-c1
    spec:
      containers:
        - name: hello-c1
          image: busybox:latest
          command: ['sh', '-c', 'echo "hello from c1" && sleep 3600']
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "50m"
